default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  host: localhost

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "app") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "app") %>_test

production:
  <<: *default
  database: <%= ENV["APP_DATABASE_NAME"] %>
  username: <%= ENV["APP_DATABASE_USER"] %>
  port: <%= ENV["APP_DATABASE_PORT"] %>
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  host: <%= ENV["APP_DATABASE_HOST"] %>
