version: '3'

volumes:
  db_dev:
services:
  db_dev:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - db_dev:/var/lib/postgresql/data/pgdata
